(function initConfig(global) {
  "use strict";

  const App = global.JimuApp = global.JimuApp || {};

  function createMessage(text, mood, suggestion, speakText) {
    return {
      text: text || "",
      speakText: speakText || text || "",
      mood: mood || "guide",
      suggestion: suggestion || "",
    };
  }

  const MSGS = ["一起动", "来打招呼", "换表情"];
  const WAITS = [
    { value: 500, label: "0.5秒" },
    { value: 1000, label: "1秒" },
    { value: 2000, label: "2秒" },
  ];
  const FACES = ["开心", "惊讶", "眨眼", "酷酷"];
  const SLOTS = [
    { id: "start", blockId: "start", label: "开始时", icon: "🚀", tip: "点运行就开始" },
    { id: "click", blockId: "clickCharacter", label: "点角色时", icon: "👆", tip: "点它才开始" },
    { id: "message", blockId: "receiveMessage", label: "收到消息", icon: "📨", tip: "听到消息就动" },
  ];
  const ACTORS = {
    cat: { id: "cat", name: "小猫", emoji: "🐱", left: "22%", bottom: 76, face: "开心" },
    rabbit: { id: "rabbit", name: "小兔", emoji: "🐰", left: "50%", bottom: 88, face: "惊讶" },
    dog: { id: "dog", name: "小狗", emoji: "🐶", left: "78%", bottom: 74, face: "酷酷" },
  };
  const SCENES = {
    meadow: { id: "meadow", name: "草地", className: "scene-meadow" },
    classroom: { id: "classroom", name: "教室", className: "scene-classroom" },
    space: { id: "space", name: "太空", className: "scene-space" },
  };
  const BLOCKS = {
    start: { label: "开始时", icon: "🚀", kind: "trigger", colorClass: "block-trigger", subText: "点运行就开始" },
    clickCharacter: { label: "点角色时", icon: "👆", kind: "trigger", colorClass: "block-trigger", subText: "点它才开始" },
    receiveMessage: { label: "收到消息", icon: "📨", kind: "trigger", colorClass: "block-trigger", subText: "听到消息就动" },
    wait: { label: "等待", icon: "⏳", kind: "control", colorClass: "block-control", subText: "等一下", paramType: "wait" },
    repeatThree: { label: "重复3次", icon: "🔁", kind: "control", colorClass: "block-control", subText: "后面做三次", badge: "×3" },
    forever: { label: "一直重复", icon: "♾️", kind: "control", colorClass: "block-control", subText: "不停地做", badge: "∞" },
    sendMessage: { label: "发送消息", icon: "📣", kind: "control", colorClass: "block-control", subText: "喊一句消息", paramType: "message" },
    sayHello: { label: "说你好", icon: "💬", kind: "speech", colorClass: "block-speech", subText: "开口打招呼" },
    sayGreat: { label: "说太棒了", icon: "🌟", kind: "speech", colorClass: "block-speech", subText: "开心夸一夸" },
    sayPlay: { label: "说一起玩", icon: "🎉", kind: "speech", colorClass: "block-speech", subText: "邀请朋友玩" },
    moveForward: { label: "向前走", icon: "👣", kind: "motion", colorClass: "block-motion", subText: "往前一点点" },
    hopOnce: { label: "跳一下", icon: "🦘", kind: "motion", colorClass: "block-motion", subText: "蹦起来" },
    backCenter: { label: "回到中间", icon: "🎯", kind: "motion", colorClass: "block-motion", subText: "回到起点" },
    spinAround: { label: "转一转", icon: "🌀", kind: "motion", colorClass: "block-motion", subText: "转个圈圈" },
    grow: { label: "变大", icon: "📈", kind: "looks", colorClass: "block-looks", subText: "大一点" },
    shrink: { label: "变小", icon: "📉", kind: "looks", colorClass: "block-looks", subText: "小一点" },
    changeFace: { label: "换表情", icon: "😄", kind: "looks", colorClass: "block-looks", subText: "变个表情", paramType: "face" },
    blink: { label: "闪一闪", icon: "✨", kind: "looks", colorClass: "block-looks", subText: "亮一下" },
  };
  const NON_TRIGGERS = Object.keys(BLOCKS).filter(function filterNonTrigger(id) {
    return BLOCKS[id].kind !== "trigger";
  });
  const TASK_ORDER = ["task1", "task2", "task3", "task4", "task5", "task6", "task7", "task8", "freeLab"];

  const TASKS = {
    task1: {
      id: "task1",
      type: "task",
      icon: "🐱",
      title: "点击小猫说你好",
      shortTitle: "小猫打招呼",
      sceneId: "classroom",
      actors: ["cat"],
      allowed: ["sayHello", "sayGreat", "moveForward", "wait", "grow"],
      intro: "把“说你好”放进小猫的点角色时里。",
      success: "太棒啦！小猫点一下就会说你好啦！",
      goal: ["cat:click:sayHello"],
      stopOnSuccess: true,
      validationPlan: [
        {
          type: "requiredSequence",
          actorId: "cat",
          slotId: "click",
          sequence: ["sayHello"],
          emptyMessage: "把说你好放到小猫的点角色时里吧。",
          wrongMessages: {
            0: function task1Wrong(ctx) {
              return ctx.slotBlocks.indexOf("sayHello") !== -1 ? "让说你好放在最前面吧。" : "小猫点一下后还没开口呢。";
            },
          },
          misplaced: [
            {
              actorId: "cat",
              slotId: "start",
              matchBlockIds: ["sayHello"],
              message: "要放在小猫的点角色时里，不是开始时哦。",
              suggestion: "切到小猫，再看点角色时。",
            },
          ],
          suggestion: "先看小猫的点角色时。",
          highlightBlocks: ["sayHello"],
        },
      ],
    },
    task2: {
      id: "task2",
      type: "task",
      icon: "🐰",
      title: "小兔开始时一直跳",
      shortTitle: "小兔一直跳",
      sceneId: "meadow",
      actors: ["rabbit"],
      allowed: ["forever", "hopOnce", "repeatThree", "wait", "sayHello"],
      intro: "让小兔一开始就一直跳起来吧。",
      success: "真棒！小兔已经会一直跳啦！",
      goal: ["loop:rabbit:start:hopOnce"],
      stopOnSuccess: false,
      validationPlan: [
        {
          type: "requiredSequence",
          actorId: "rabbit",
          slotId: "start",
          sequence: ["forever", "hopOnce"],
          emptyMessage: "先把一直重复放进小兔的开始时里。",
          wrongMessages: {
            0: "要先放一直重复，这样才会不停跳。",
            1: "一直重复后面要接跳一下。",
          },
          suggestion: "先在小兔的开始时里放两个积木。",
          highlightBlocks: ["forever", "hopOnce"],
        },
      ],
    },
    task3: {
      id: "task3",
      type: "task",
      icon: "🐶",
      title: "小狗开始时向前走",
      shortTitle: "小狗往前走",
      sceneId: "meadow",
      actors: ["dog"],
      allowed: ["moveForward", "hopOnce", "wait", "grow", "sayPlay"],
      intro: "让小狗一开始就往前走。",
      success: "真棒！小狗已经迈步出发啦！",
      goal: ["dog:start:moveForward"],
      stopOnSuccess: true,
      validationPlan: [
        {
          type: "requiredSequence",
          actorId: "dog",
          slotId: "start",
          sequence: ["moveForward"],
          emptyMessage: "把向前走放到小狗的开始时里吧。",
          wrongMessages: { 0: "把向前走放到小狗的开始时里吧。" },
          suggestion: "先看小狗的开始时。",
          highlightBlocks: ["moveForward"],
        },
      ],
    },
    task4: {
      id: "task4",
      type: "task",
      icon: "⏳",
      title: "小猫等待一下再夸奖",
      shortTitle: "小猫等一下",
      sceneId: "classroom",
      actors: ["cat"],
      allowed: ["wait", "sayGreat", "sayHello", "moveForward", "blink"],
      intro: "先等一下，再让小猫说太棒了。",
      success: "太好了！你已经会安排先后顺序啦！",
      goal: ["cat:start:sayGreat"],
      stopOnSuccess: true,
      validationPlan: [
        {
          type: "requiredSequence",
          actorId: "cat",
          slotId: "start",
          sequence: ["wait", "sayGreat"],
          emptyMessage: "先在小猫的开始时里放等待。",
          wrongMessages: {
            0: "先等一下，再夸奖哦。",
            1: "等待后面要接说太棒了。",
          },
          suggestion: "先在小猫的开始时里安排先后顺序。",
          highlightBlocks: ["wait", "sayGreat"],
        },
      ],
    },
    task5: {
      id: "task5",
      type: "task",
      icon: "🔁",
      title: "小兔重复3次跳一下",
      shortTitle: "小兔跳三次",
      sceneId: "meadow",
      actors: ["rabbit"],
      allowed: ["repeatThree", "hopOnce", "moveForward", "wait", "sayPlay"],
      intro: "让小兔开始后连续跳三次。",
      success: "你会用重复3次啦！小兔跳得真整齐！",
      goal: ["loop3:rabbit:start:hopOnce"],
      stopOnSuccess: true,
      validationPlan: [
        {
          type: "requiredSequence",
          actorId: "rabbit",
          slotId: "start",
          sequence: ["repeatThree", "hopOnce"],
          emptyMessage: "先把重复3次放进小兔的开始时里。",
          wrongMessages: {
            0: "要先放重复3次。",
            1: "重复3次后面要接跳一下。",
          },
          suggestion: "先把重复积木放在前面。",
          highlightBlocks: ["repeatThree", "hopOnce"],
        },
      ],
    },
    task6: {
      id: "task6",
      type: "task",
      icon: "😄",
      title: "点小狗变大再换表情",
      shortTitle: "小狗变大变脸",
      sceneId: "classroom",
      actors: ["dog"],
      allowed: ["grow", "changeFace", "shrink", "blink", "sayGreat"],
      intro: "点一下小狗，让它先变大，再换表情。",
      success: "真棒！小狗已经会变大又变脸啦！",
      goal: ["dog:click:changeFace"],
      stopOnSuccess: true,
      validationPlan: [
        {
          type: "requiredSequence",
          actorId: "dog",
          slotId: "click",
          sequence: ["grow", "changeFace"],
          emptyMessage: "把变大和换表情放到小狗的点角色时里。",
          wrongMessages: {
            0: "先让小狗变大，再换表情。",
            1: "变大后面要接换表情。",
          },
          misplaced: [
            {
              actorId: "dog",
              slotId: "start",
              matchBlockIds: ["grow", "changeFace"],
              message: "这次要点一下小狗才开始哦。",
              suggestion: "切到小狗的点角色时。",
            },
          ],
          suggestion: "先看小狗的点角色时。",
          highlightBlocks: ["grow", "changeFace"],
        },
      ],
    },
    task7: {
      id: "task7",
      type: "task",
      icon: "📣",
      title: "小猫叫小狗来打招呼",
      shortTitle: "消息打招呼",
      sceneId: "classroom",
      actors: ["cat", "dog"],
      allowed: ["sendMessage", "sayHello", "sayPlay", "wait", "changeFace"],
      intro: "让小猫先发来打招呼，小狗听见后说你好。",
      success: "太棒啦！你已经会让朋友听消息啦！",
      goal: ["dog:message:sayHello"],
      stopOnSuccess: true,
      validationPlan: [
        {
          type: "requiredSequence",
          actorId: "cat",
          slotId: "start",
          sequence: ["sendMessage"],
          emptyMessage: "先让小猫在开始时发消息吧。",
          wrongMessages: { 0: "先让小猫在开始时发消息吧。" },
          suggestion: "先看小猫的开始时。",
          highlightBlocks: ["sendMessage"],
        },
        {
          type: "blockParam",
          actorId: "cat",
          slotId: "start",
          index: 0,
          blockId: "sendMessage",
          expectedParam: "来打招呼",
          message: "这次小猫要发来打招呼。",
          suggestion: "点一下消息参数，把它切到来打招呼。",
          highlightBlocks: ["sendMessage"],
        },
        {
          type: "messageBinding",
          actorId: "dog",
          expectedMessage: "来打招呼",
          message: "小狗要听来打招呼这句消息。",
          suggestion: "点一下收到消息右边的小按钮，切到来打招呼。",
        },
        {
          type: "requiredSequence",
          actorId: "dog",
          slotId: "message",
          sequence: ["sayHello"],
          emptyMessage: "小狗收到消息后要说你好。",
          wrongMessages: { 0: "小狗收到消息后要说你好。" },
          suggestion: "再看一眼小狗的收到消息脚本槽。",
          highlightBlocks: ["sayHello"],
        },
      ],
    },
    task8: {
      id: "task8",
      type: "task",
      icon: "🌌",
      title: "三角色接力表演",
      shortTitle: "接力表演",
      sceneId: "space",
      actors: ["cat", "rabbit", "dog"],
      allowed: ["sendMessage", "changeFace", "hopOnce", "sayPlay", "blink", "wait"],
      intro: "让小猫一开始发一起动，小狗换表情，小兔跳一下。",
      success: "真棒！三位朋友已经会接力合作啦！",
      goal: ["dog:message:changeFace", "rabbit:message:hopOnce"],
      stopOnSuccess: true,
      validationPlan: [
        {
          type: "requiredSequence",
          actorId: "cat",
          slotId: "start",
          sequence: ["sendMessage"],
          emptyMessage: "先让小猫一开始发出一起动。",
          wrongMessages: { 0: "先让小猫一开始发出一起动。" },
          suggestion: "先看小猫的开始时。",
          highlightBlocks: ["sendMessage"],
        },
        {
          type: "blockParam",
          actorId: "cat",
          slotId: "start",
          index: 0,
          blockId: "sendMessage",
          expectedParam: "一起动",
          message: "这次小猫要发一起动。",
          suggestion: "点一下消息参数，把它切到一起动。",
          highlightBlocks: ["sendMessage"],
        },
        {
          type: "messageBinding",
          actorId: "dog",
          expectedMessage: "一起动",
          message: "小狗要听一起动这句消息。",
          suggestion: "点一下小狗收到消息右边的小按钮。",
        },
        {
          type: "requiredSequence",
          actorId: "dog",
          slotId: "message",
          sequence: ["changeFace"],
          emptyMessage: "小狗听见消息后要换表情。",
          wrongMessages: { 0: "小狗听见消息后要换表情。" },
          suggestion: "再看一眼小狗的收到消息脚本槽。",
          highlightBlocks: ["changeFace"],
        },
        {
          type: "messageBinding",
          actorId: "rabbit",
          expectedMessage: "一起动",
          message: "小兔也要听一起动。",
          suggestion: "点一下小兔收到消息右边的小按钮。",
        },
        {
          type: "requiredSequence",
          actorId: "rabbit",
          slotId: "message",
          sequence: ["hopOnce"],
          emptyMessage: "小兔收到消息后要跳一下。",
          wrongMessages: { 0: "小兔收到消息后要跳一下。" },
          suggestion: "再看一眼小兔的收到消息脚本槽。",
          highlightBlocks: ["hopOnce"],
        },
      ],
    },
    freeLab: {
      id: "freeLab",
      type: "free",
      icon: "🧪",
      title: "自由实验室",
      shortTitle: "自由实验室",
      sceneId: "meadow",
      actors: ["cat", "rabbit", "dog"],
      allowed: NON_TRIGGERS.slice(),
      intro: "想怎么搭都可以。选角色，拖积木，点运行。",
      success: "自由实验室开始啦！",
      goal: [],
      stopOnSuccess: false,
      validationPlan: [],
    },
  };

  const PROMPTS = [
    { id: "p1", label: "让小猫说你好", taskId: "task1", actorId: "cat", blocks: ["sayHello"], reply: "我听懂啦，你想让小猫说你好。看看小猫的点角色时吧。" },
    { id: "p2", label: "让小兔一直跳", taskId: "task2", actorId: "rabbit", blocks: ["forever", "hopOnce"], reply: "我听懂啦，你想让小兔一直跳。先看小兔的开始时。" },
    { id: "p3", label: "让小狗往前走", taskId: "task3", actorId: "dog", blocks: ["moveForward"], reply: "我听懂啦，你想让小狗往前走。" },
    { id: "p4", label: "让小猫等一下再夸奖", taskId: "task4", actorId: "cat", blocks: ["wait", "sayGreat"], reply: "我听懂啦，你想让小猫先等等，再夸奖。" },
    { id: "p5", label: "让小兔跳三次", taskId: "task5", actorId: "rabbit", blocks: ["repeatThree", "hopOnce"], reply: "我听懂啦，你想让小兔跳三次。" },
    { id: "p6", label: "点小狗变大变脸", taskId: "task6", actorId: "dog", blocks: ["grow", "changeFace"], reply: "我听懂啦，你想点小狗让它变大又变脸。" },
    { id: "p7", label: "让小猫叫小狗打招呼", taskId: "task7", actorId: "cat", blocks: ["sendMessage", "sayHello"], reply: "我听懂啦，你想让小猫叫小狗打招呼。" },
    { id: "p8", label: "让大家接力表演", taskId: "task8", actorId: "cat", blocks: ["sendMessage", "changeFace", "hopOnce"], reply: "我听懂啦，你想让大家接力表演。" },
    { id: "pf1", label: "我想自由搭积木", taskId: "freeLab", actorId: "cat", blocks: ["sendMessage", "hopOnce", "blink"], reply: "我听懂啦，你想自由搭积木。" },
    { id: "pf2", label: "让大家一起动", taskId: "freeLab", actorId: "cat", sceneId: "space", blocks: ["sendMessage", "hopOnce", "changeFace"], reply: "我听懂啦，你想让大家一起动。" },
    { id: "pf3", label: "让小狗变大", taskId: "freeLab", actorId: "dog", blocks: ["grow", "sayGreat"], reply: "我听懂啦，你想让小狗变大。" },
  ];

  App.createMessage = createMessage;
  App.config = {
    APP_NAME: "积木小老师",
    STORAGE_KEY: "jimu-app:workspace:v2",
    STORAGE_VERSION: 2,
    MAX_LOGS: 80,
    MSGS: MSGS,
    WAITS: WAITS,
    FACES: FACES,
    SLOTS: SLOTS,
    ACTORS: ACTORS,
    SCENES: SCENES,
    BLOCKS: BLOCKS,
    NON_TRIGGERS: NON_TRIGGERS,
    TASK_ORDER: TASK_ORDER,
    TASKS: TASKS,
    PROMPTS: PROMPTS,
    BRAND_PHOTO_CANDIDATES: [
      "assets/brand/brand-photo.png",
      "assets/brand/brand-photo.jpg",
      "assets/brand/brand-photo.jpeg",
      "assets/brand/brand-photo.webp",
    ],
    DEBUG_DELAY_OPTIONS: [0, 300, 800, 1500],
  };
})(window);
